# Generated by Django 5.2.3 on 2025-07-03 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تمرین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدئو')),
                ('is_cardio', models.BooleanField(default=False, verbose_name='آیا کاردیو است؟')),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': 'تمرینات',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام برنامه تمرینی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات برنامه')),
                ('is_public', models.BooleanField(default=False, verbose_name='آیا عمومی است؟')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'برنامه تمرینی',
                'verbose_name_plural': 'برنامه\u200cهای تمرینی',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise', verbose_name='تمرین')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutplan', verbose_name='برنامه تمرینی')),
            ],
            options={
                'verbose_name': 'تمرین در برنامه',
                'verbose_name_plural': 'تمرینات در برنامه\u200cها',
                'ordering': ['order'],
                'unique_together': {('workout_plan', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_plans', through='workouts.WorkoutPlanExercise', to='workouts.exercise', verbose_name='تمرینات'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('date', models.DateField(verbose_name='تاریخ جلسه')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('workout_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutplan', verbose_name='برنامه تمرینی (اختیاری)')),
            ],
            options={
                'verbose_name': 'جلسه تمرینی',
                'verbose_name_plural': 'جلسات تمرینی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('set_number', models.PositiveIntegerField(verbose_name='شماره ست')),
                ('reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تکرار')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن (کیلوگرم)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مسافت (کیلومتر)')),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان (ثانیه)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای ست')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise', verbose_name='تمرین')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutsession', verbose_name='جلسه تمرینی')),
            ],
            options={
                'verbose_name': 'ست',
                'verbose_name_plural': 'ست\u200cها',
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='توسط مربی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='workouts.workoutplan', verbose_name='برنامه تمرینی')),
            ],
            options={
                'verbose_name': 'انتساب برنامه تمرینی',
                'verbose_name_plural': 'انتساب برنامه\u200cهای تمرینی',
                'unique_together': {('user', 'workout_plan', 'start_date')},
            },
        ),
    ]
