# Generated by Django 5.2.3 on 2025-07-11 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='load_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='بار کل (کیلوگرم)'),
        ),
        migrations.AddField(
            model_name='set',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان استراحت (ثانیه)'),
        ),
        migrations.AddField(
            model_name='set',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='میزان درک فشار (RPE 1-10)'),
        ),
    ]
