# Generated by Django 5.2.3 on 2025-07-11 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_set_load_kg_set_rest_seconds_set_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مسافت پیش\u200cفرض (کیلومتر)'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_reps',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تکرار پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان استراحت پیش\u200cفرض (ثانیه)'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE پیش\u200cفرض (1-10)'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_sets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد ست پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پیش\u200cفرض (ثانیه)'),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='default_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن پیش\u200cفرض (کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_plans', through='workouts.WorkoutPlanExercise', through_fields=('workout_plan', 'exercise'), to='workouts.exercise', verbose_name='تمرینات'),
        ),
        migrations.AlterModelTable(
            name='workoutplan',
            table='workouts_workoutplan',
        ),
        migrations.AlterModelTable(
            name='workoutplanexercise',
            table='workouts_plan_exercise',
        ),
    ]
