# Generated by Django 5.2.3 on 2025-07-12 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutplanexercise_default_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_number'], 'verbose_name': 'Set', 'verbose_name_plural': 'Sets'},
        ),
        migrations.AlterModelOptions(
            name='userworkoutplanassignment',
            options={'verbose_name': 'User Workout Plan Assignment', 'verbose_name_plural': 'User Workout Plan Assignments'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'verbose_name': 'Workout Plan', 'verbose_name_plural': 'Workout Plans'},
        ),
        migrations.AlterModelOptions(
            name='workoutplanexercise',
            options={'ordering': ['order'], 'verbose_name': 'Exercise in Plan', 'verbose_name_plural': 'Exercises in Plans'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Workout Session', 'verbose_name_plural': 'Workout Sessions'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_cardio',
            field=models.BooleanField(default=False, verbose_name='Is Cardio?'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Exercise Name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Link'),
        ),
        migrations.AlterField(
            model_name='set',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_performed', to='workouts.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='load_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Load (kg)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Set Notes'),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reps'),
        ),
        migrations.AlterField(
            model_name='set',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rest Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE (1-10)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(verbose_name='Set Number'),
        ),
        migrations.AlterField(
            model_name='set',
            name='time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutsession', verbose_name='Workout Session'),
        ),
        migrations.AlterField(
            model_name='userworkoutplanassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By Coach'),
        ),
        migrations.AlterField(
            model_name='userworkoutplanassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='userworkoutplanassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='userworkoutplanassignment',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='userworkoutplanassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userworkoutplanassignment',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='workouts.workoutplan', verbose_name='Workout Plan'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Plan Description'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_plans', through='workouts.WorkoutPlanExercise', to='workouts.exercise', verbose_name='Exercises'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public?'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Workout Plan Name'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Default Distance (km)'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_notes',
            field=models.TextField(blank=True, verbose_name='Default Notes'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_reps',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default Reps'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default Rest Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Default RPE (1-10)'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_sets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default Sets'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='default_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Default Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='workoutplanexercise',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutplan', verbose_name='Workout Plan'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(verbose_name='Session Date'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutplan', verbose_name='Workout Plan (Optional)'),
        ),
        migrations.AlterModelTable(
            name='workoutplan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workoutplanexercise',
            table=None,
        ),
    ]
